### ISSUE TITLE
Zclassic eleos Mac 

### ISSUE THREAD

**Issue by Stigermann** [z-classic/zclassic#67]
When I open the wallet, it gives me this error:

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:549:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:200:20)
    at ReadStream.open (fs.js:1782:6)
    at new ReadStream (fs.js:1769:10)
    at Object.fs.createReadStream (fs.js:1723:10)
    at Object.<anonymous> (/Applications/eleos.app/Contents/Resources/app/wallet.js:35:49)
    at Object.<anonymous> (/Applications/eleos.app/Contents/Resources/app/wallet.js:99:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by MellonMan** [comment]
I'm running into the same issue - any help would be greatly appreciated, don't want to miss out on the 1:1! 
Thanks guys!

**Comment by joshuayabut** [comment]
Can you try the latest Eleos version? https://github.com/zencashio/eleos/releases

**Comment by koadowsett** [comment]
Hey guys how do you view the private keys on the Eleos wallet?

**Comment by MellonMan** [comment]
Thanks for responding!

I think ended installing on a different computer and it worked fine.
thanks!

**Comment by aayanl** [comment]
@koadowsett do `./zcl-cli dumpprivkey ADDRESSHERE`

**Comment by aayanl** [comment]
good to know @MellonMan

**Comment by koadowsett** [comment]
thanks @aayanl do you do that in console? and then does it show up in that screen? sorry im a complete newb, just wanna cash in on zen coin. i appreciate your help
